parameters:
  - name: terraformVersion
    type: string
    default: 'latest'
  - name: agentPool
    displayName: 'Agent Pool Selection'
    type: string
    default: Self-Hosted
    values:
    - Self-Hosted
    - Oracle-Cloud

trigger:
- none

stages:
  - stage: 'OCIObjectStorage'
    dependsOn: []
    displayName: 'OCI Object Storage'

    jobs:
      - job: 'terraforminitplan'
        displayName: 'Initialize and Plan Terraform for OCI Object Storage'
        pool: ${{ parameters.agentPool }}

        steps:

          - task: TerraformInstaller@0
            displayName: 'Terraform Install'
            inputs:
              terraformVersion: ${{ parameters.terraformVersion }}
  
          - task: CmdLine@2       
            inputs:
              script: |
                terraform init -backend-config="/terraform/variables/terraform-oracle/object_storage/backend_oracle_object_storage.tf"
              workingDirectory: '$(System.DefaultWorkingDirectory)/object_storage/'

          - task: CmdLine@2
            inputs:
              script: |
                terraform plan -var-file="/terraform/variables/terraform-oracle/object_storage/prod.tfvars" -out ${BUILD_BUILDNUMBER}.tfplan
              workingDirectory: '$(System.DefaultWorkingDirectory)/object_storage/'

          - task: ArchiveFiles@2
            condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
            displayName: 'Create Plan Artifact'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/object_storage/'
              includeRootFolder: false
              archiveType: 'tar'
              tarCompression: 'gz'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).tgz'
              replaceExistingArchive: true
            
          - task: PublishPipelineArtifact@1
            condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
            displayName: 'Publish Plan Artifact'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'oci-object-storage-plan'

  - stage: 'OCIObjectStorageApply'
    dependsOn: 'OCIObjectStorage'
    displayName: OCI Object Storage Apply

    jobs:
      - deployment: 'TerraformApplyOCICoreInstance'   
        displayName: ' Apply Terraform for OCI Object Storage'
        pool: ${{ parameters.agentPool }}
        environment: 'Oracle-Prod'
        strategy:
          runOnce:
            deploy:
              steps:

              - task: TerraformInstaller@0
                displayName: 'Terraform Install'
                inputs:
                  terraformVersion: ${{ parameters.terraformVersion }}
                  
              - task: ExtractFiles@1
                displayName: 'Extract Plan Artifact'
                inputs:
                  archiveFilePatterns: '$(Pipeline.Workspace)/oci-object-storage-plan/$(Build.BuildNumber).tgz'
                  destinationFolder: '$(System.DefaultWorkingDirectory)/object_storage/'
                  cleanDestinationFolder: true

              - task: CmdLine@2
                inputs:
                  script: |
                    terraform apply ${BUILD_BUILDNUMBER}.tfplan
                  workingDirectory: '$(System.DefaultWorkingDirectory)/object_storage/'