parameters:
  - name: terraformVersion
    type: string
    default: 'latest'
  - name: agentPool
    displayName: 'Agent Pool Selection'
    type: string
    default: Self-Hosted
    values:
    - Self-Hosted
    - Oracle-Cloud

trigger:
- none

stages:
  - stage: 'OCI_Networking'
    dependsOn: []
    displayName: 'OCI Networking'

    jobs:
      - job: 'terraforminitplan'
        displayName: 'Initialize and Plan Terraform for OCI Networking'
        pool: ${{ parameters.agentPool }}

        steps:

          - task: TerraformInstaller@0
            displayName: 'Terraform Install'
            inputs:
              terraformVersion: ${{ parameters.terraformVersion }}
  
          - task: CmdLine@2       
            inputs:
              script: |
                terraform init -backend-config="/terraform/variables/terraform-oracle/networking/backend_oracle_networking.tf"
              workingDirectory: '$(System.DefaultWorkingDirectory)/01_networking/'

          - task: CmdLine@2
            inputs:
              script: |
                terraform plan -var-file="/terraform/variables/terraform-oracle/networking/prod.tfvars" -out ${BUILD_BUILDNUMBER}.tfplan
              workingDirectory: '$(System.DefaultWorkingDirectory)/01_networking/'

          - task: ArchiveFiles@2
            condition: succeeded()
            displayName: 'Create Plan Artifact'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/01_networking/'
              includeRootFolder: false
              archiveType: 'tar'
              tarCompression: 'gz'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).tgz'
              replaceExistingArchive: true
            
          - task: PublishPipelineArtifact@1
            condition: succeeded()
            displayName: 'Publish Plan Artifact'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'oci-networking-plan'

  - stage: 'OCI_Networking_Apply'
    dependsOn: 'OCI_Networking'
    displayName: OCI Networking Apply

    jobs:
      - deployment: 'TerraformApplyOCINetworking'   
        displayName: ' Apply Terraform for OCI Networking'
        pool: ${{ parameters.agentPool }}
        environment: 'Oracle-Prod'
        strategy:
          runOnce:
            deploy:
              steps:

              - task: TerraformInstaller@0
                displayName: 'Terraform Install'
                inputs:
                  terraformVersion: ${{ parameters.terraformVersion }}
                  
              - task: ExtractFiles@1
                displayName: 'Extract Plan Artifact'
                inputs:
                  archiveFilePatterns: '$(Pipeline.Workspace)/oci-networking-plan/$(Build.BuildNumber).tgz'
                  destinationFolder: '$(System.DefaultWorkingDirectory)/01_networking/'
                  cleanDestinationFolder: true

              - task: CmdLine@2
                inputs:
                  script: |
                    terraform apply ${BUILD_BUILDNUMBER}.tfplan
                  workingDirectory: '$(System.DefaultWorkingDirectory)/01_networking/'
