parameters:
  - name: terraformVersion
    type: string
    default: 'latest'
  - name: agentPool
    displayName: 'Agent Pool Selection'
    type: string
    default: Self-Hosted
    values:
    - Self-Hosted
    - Oracle-Cloud

trigger:
- none

stages:
  - stage: 'OCICoreInstance'
    dependsOn: []
    displayName: 'OCI Core Instance'

    jobs:
      - job: 'terraforminitplan'
        displayName: 'Initialize and Plan Terraform for OCI Core Instance'
        pool: ${{ parameters.agentPool }}

        steps:

          - task: TerraformInstaller@1
            displayName: 'Terraform Install'
            inputs:
              terraformVersion: ${{ parameters.terraformVersion }}

          - task: CmdLine@2
            name: terraformInit
            inputs:
              script: |
                terraform init -backend-config="/terraform/variables/terraform-oracle/core_instance/backend_oracle_core_instance.tf"
              workingDirectory: '$(System.DefaultWorkingDirectory)/core_instance/'

          - task: CmdLine@2
            name: terraformPlan
            inputs:
              script: |
                terraform plan -var-file="/terraform/variables/terraform-oracle/core_instance/prod.tfvars" -out ${BUILD_BUILDNUMBER}.tfplan -detailed-exitcode

                if [ $? -eq 2 ]; then
                  echo "##vso[task.setvariable variable=planChanged;isOutput=true]true"
                else
                  echo "##vso[task.setvariable variable=planChanged;isOutput=true]false"
                fi 
              workingDirectory: '$(System.DefaultWorkingDirectory)/core_instance/'

          - task: ArchiveFiles@2
            condition: succeeded()
            displayName: 'Create Plan Artifact'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/core_instance/'
              includeRootFolder: false
              archiveType: 'tar'
              tarCompression: 'gz'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).tgz'
              replaceExistingArchive: true

          - task: PublishPipelineArtifact@1
            condition: succeeded()
            displayName: 'Publish Plan Artifact'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'oci-core-instance-plan'

  - stage: 'OCICoreInstanceApply'
    dependsOn: 'OCICoreInstance'
    condition: and(succeeded(), eq(dependencies.OCICoreInstance.outputs['terraforminitplan.terraformPlan.planChanged'], 'true'))
    displayName: OCI Core Instance Apply

    jobs:
      - deployment: 'TerraformApplyOCICoreInstance'
        displayName: ' Apply Terraform for OCI COre Instance'
        pool: ${{ parameters.agentPool }}
        environment: 'Oracle-Prod'
        strategy:
          runOnce:
            deploy:
              steps:

              - task: TerraformInstaller@1
                displayName: 'Terraform Install'
                inputs:
                  terraformVersion: ${{ parameters.terraformVersion }}

              - task: ExtractFiles@1
                displayName: 'Extract Plan Artifact'
                inputs:
                  archiveFilePatterns: '$(Pipeline.Workspace)/oci-core-instance-plan/$(Build.BuildNumber).tgz'
                  destinationFolder: '$(System.DefaultWorkingDirectory)/core_instance/'
                  cleanDestinationFolder: true

              - task: CmdLine@2
                inputs:
                  script: |
                    terraform apply ${BUILD_BUILDNUMBER}.tfplan
                  workingDirectory: '$(System.DefaultWorkingDirectory)/core_instance/'
